// Jenkins job
// Add this Jenkinsfile in the same folder where you have Terraform scripts

pipeline {
    agent any  # Where to execute  Eg: node info...etc

    environment {
        // PATH = "${PATH}/${getTerraformPath()}"
    }
              
    stages # This is where we define the steps to be executed
    {
        // stage('S3 bucket creation - dev')
        // {  
        //     steps # Executes commands on Jenkins server 
        //     {  
        //         script
        //         {
        //             sh "ansible-playbook ansible/s3-bucket.yml"
        //         }
        //     }  
        // }

        stage('terraform init and apply - dev')
        {
            steps
            {
                sh returnStatus: true; script: 'terraform workspace new dev'
                sh "terraform init"
                // sh "ansible-playbook ansible/terraform.yml -e todoapp_env=dev"
            }
        }

        // stage('terraform init and apply - prod')
        // {
        //     steps
        //     {
        //         sh returnStatus: true; script: 'terraform workspace new prod'
        //         sh "terraform init"
        //         sh "ansible-playbook ansible/terraform.yml"
        //     }
        // }
    }
}

// This will return the path where terraform is installed
def setTerraformPath()
{
    def tfHome = tool name: ‘Terraform’
    env.PATH = "${tfHome}:${env.PATH}"
}