---
- hosts: localhost

  vars:

    # Below are default values. 
    # Real values can be given while running playbook

    aws_state: present
    s3_bucket: "todoapp-terraform-state-bucket"
    key: terraform_todoapp_state  # This is the key
    region: ap-south-1
    todoapp_env: dev
    
  tasks:
    - shell: ps -eo pcpu,user,args | sort -r -k1 | head -n5
      register: ps
    - debug: var=ps.stdout_lines
    - name: Run terraform scripts
      terraform: # Ansible module name for terraform
        project_path:  "./dev" # path to find terraform scripts
        state: "{{ aws_state }}"
        force_init: true

        # backend-config:
        #   bucket: "{{ s3_bucket }}"
        #   key: "{{ key }}"
        #   region: "{{ region }}"

        # variables_file: "{{ todoapp_env }}.tfvars"
        workspace: "{{ todoapp_env }}"